spring.application.name=Grocery_Store
spring.datasource.url=jdbc:mysql://localhost:3306/project_grocery_store?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

razorpay.key.id=rzp_test_RuvUbr2zSaWSnW
razorpay.key.secret=7von5zveIh6oQ66k3PCqXAmR

